services:

  bundle-update:
    image: ruby:2.7.4
    working_dir: /usr/site
    command: bundle update
    profiles:
      - update
    volumes:
      - type: volume
        source: gem_home
        target: /usr/local/bundle
      - type: bind
        source: .
        target: /usr/site

  blog:
    depends_on:
      bundle-update:
        condition: service_completed_successfully
        required: false
    image: ruby:2.7.4
    working_dir: /usr/site
    command: bundle exec jekyll serve --drafts --host=0.0.0.0
    ports:
      - 4000:4000
    volumes:
      - type: volume
        source: gem_home
        target: /usr/local/bundle
      - type: bind
        source: .
        target: /usr/site

volumes:
  gem_home:
