services:

  install:
    extends:
      file: common.yaml
      service: common
    command: gem install jekyll --version 4.3.3
    profiles:
      - install

  update:
    extends:
      file: common.yaml
      service: site
    depends_on:
      install:
        condition: service_completed_successfully
        required: false
    command: bundle update
    profiles:
      - install
      - update

  blog:
    extends:
      file: common.yaml
      service: site
    depends_on:
      update:
        condition: service_completed_successfully
        required: false
    command: jekyll serve --drafts --host=0.0.0.0 --incremental
    ports:
      - 4000:4000

  plantuml:
    image: plantuml/plantuml-server:jetty
    ports:
      - 8080:8080

volumes:
  gem_home:
